# Generated by Django 3.2.12 on 2022-03-23 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='idea',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='content_en',
            field=models.TextField(db_tablespace='', verbose_name='Content (English)'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title_en',
            field=models.CharField(db_tablespace='', max_length=200, verbose_name='Title (English)'),
        ),
    ]
