# Generated by Django 3.2.12 on 2022-03-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20220323_1706'),
        ('ideas', '0004_alter_idea_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='categories',
        ),
        migrations.AddField(
            model_name='idea',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='ideas', to='categories.Category', verbose_name='Categories'),
        ),
    ]
