# Generated by Django 3.2.12 on 2022-03-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20220323_1706'),
        ('ideas', '0005_auto_20220323_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='categories',
        ),
        migrations.AddField(
            model_name='idea',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_ideas', to='categories.category', verbose_name='Categories'),
        ),
    ]
