# Generated by Django 3.2.12 on 2022-04-11 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('categories', '0002_auto_20220323_1706'),
        ('ideas', '0007_auto_20220409_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(default='', help_text='Please enter the ID of the related object.', max_length=255, verbose_name='Related object')),
                ('owner_object_id', models.CharField(default='', help_text='Please enter the ID of the related object.', max_length=255, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.RemoveField(
            model_name='idea',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='uuid',
        ),
        migrations.AddField(
            model_name='idea',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='meta_author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='idea',
            name='meta_copyright',
            field=models.CharField(blank=True, max_length=255, verbose_name='Copyright'),
        ),
        migrations.AddField(
            model_name='idea',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='idea',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Separate keywords with commas.', max_length=255, verbose_name='Keywords'),
        ),
        migrations.RemoveField(
            model_name='idea',
            name='categories',
        ),
        migrations.AddField(
            model_name='idea',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_ideas', to='categories.category', verbose_name='Categories'),
        ),
        migrations.AddConstraint(
            model_name='idea',
            constraint=models.UniqueConstraint(condition=models.Q(('author', None), _negated=True), fields=('title_en',), name='unique_titles_for_each_author'),
        ),
        migrations.AddConstraint(
            model_name='idea',
            constraint=models.CheckConstraint(check=models.Q(('title_en__iregex', '^\\S.*\\S$')), name='title_has_no_leading_and_trailing_whitespaces'),
        ),
        migrations.AddField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(help_text='Please select the type (model) for the relation, you want to build.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name="Related object's type (model)"),
        ),
        migrations.AddField(
            model_name='like',
            name='owner_content_type',
            field=models.ForeignKey(help_text='Please select the type (model) for the relation, you want to build.', limit_choices_to={'model__in': ('user', 'group')}, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='contenttypes.contenttype', verbose_name="Owner's type (model)"),
        ),
    ]
