# Generated by Django 3.2.12 on 2022-04-11 17:16

from django.db import migrations, models
import myproject.apps.ideas.models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0009_auto_20220411_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='picture',
            field=models.ImageField(null=True, upload_to=myproject.apps.ideas.models.upload_to, verbose_name='Picture'),
        ),
    ]
