# Generated by Django 3.2.12 on 2022-04-11 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0010_alter_idea_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='content_bg',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_cs',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_da',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_el',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_es',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_et',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_fi',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_ga',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_hr',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_hu',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_it',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_lt',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_lv',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_mt',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_nl',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_pl',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_pt',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_ro',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_sk',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_sl',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='content_sv',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_bg',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_cs',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_da',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_el',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_et',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_fi',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_ga',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_hr',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_hu',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_it',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_lt',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_lv',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_mt',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_nl',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_pt',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_ro',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_sk',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_sl',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='title_sv',
        ),
        migrations.AddField(
            model_name='idea',
            name='content',
            field=models.TextField(default='', verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='IdeaTranslations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=7, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='ideas.idea', verbose_name='Idea')),
            ],
            options={
                'verbose_name': 'Idea Translations',
                'verbose_name_plural': 'Idea Translations',
                'ordering': ['language'],
                'unique_together': {('idea', 'language')},
            },
        ),
    ]
