# Generated by Django 3.2.12 on 2022-05-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20220323_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title_bg',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_cs',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_da',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_el',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_et',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_fi',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_ga',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_hr',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_hu',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_it',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_lt',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_lv',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_mt',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_nl',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_pt',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_ro',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_sk',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_sl',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_sv',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='a', max_length=200, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CategoryTranslations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=7, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='categories.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category Translations',
                'verbose_name_plural': 'Category Translations',
                'ordering': ['language'],
                'unique_together': {('category', 'language')},
            },
        ),
    ]
